#!/usr/bin/env bash
#
# Run redex in a container
#
# This script will attempt to mirror the host paths by using volumes for the
# following paths:
#   * $(pwd)
#   * $HOME if it's set
#

set -e

IMAGE="yongjhih/firefox"

# Setup options for connecting to docker host
if [ -z "$DOCKER_HOST" ]; then
    DOCKER_HOST="/var/run/docker.sock"
fi
if [ -S "$DOCKER_HOST" ]; then
    DOCKER_ADDR="-v $DOCKER_HOST:$DOCKER_HOST -e DOCKER_HOST"
else
    DOCKER_ADDR="-e DOCKER_HOST -e DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH"
fi


# Setup volume mounts for compose config and context
if [ "$(pwd)" != '/' ]; then
    VOLUMES="-v $(pwd):$(pwd)"
fi
if [ -n "$HOME" ]; then
    VOLUMES="$VOLUMES -v $HOME:$HOME -v $HOME:/root -v $HOME:/home/ubuntu" # mount $HOME in /root to share docker.config
fi

# Only allocate tty if we detect one
if [ -t 1 ]; then
    DOCKER_RUN_OPTIONS="-t"
fi
if [ -t 0 ]; then
    DOCKER_RUN_OPTIONS="$DOCKER_RUN_OPTIONS -i"
fi

xhost si:localuser:$USER

# Set up PulseAudio Cookie
if [ x"$(pax11publish -d)" = x ]; then
    start-pulseaudio-x11
fi

#echo -- --user `id -u`:`getent group video | cut -d: -f3`

                #-w "$(pwd)" \
exec docker run --rm $DOCKER_RUN_OPTIONS \
                $DOCKER_ADDR \
                $VOLUMES \
                -v /dev/bus/usb \
                -v /dev/kvm \
                -v /dev/snd \
                -v /run/dbus \
                -v /dev/shm \
                -v /tmp/.X11-unix \
                -e UID=$(id -u) \
                -e GID=$(id -g) \
                -e DISPLAY=$DISPLAY \
                -e PULSE_SERVER=tcp:localhost:4713 \
                --group-add audio \
                --group-add video \
                -v $XAUTHORITY:/home/ubuntu/.Xauthority \
                --net=host \
                --privileged \
                $IMAGE \
                firefox "$@"
